POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Bob Lemon",
    "number": "39-68-1525897"
}

###

POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "number": "39-68-1525897"
}

###

POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Bob Lemon"
}

